#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_MAIN                                101
#define IDD_PLAYBACK                            103
#define IDD_INTEGR                              105
#define IDR_MENU1                               106
#define ID_ACCEL                                107
#define IDD_SETTINGS                            111
#define IDD_URL                                 113
#define IDR_CONTEXT_MENU                        115
#define IDC_URL                                 1001
#define ID_DELETE                               1002
#define ID_MINIMIZE                             1003
#define IDC_VOLUME                              1005
#define IDC_SCROLLBAR                           1006
#define ID_ADDFILE                              1007
#define IDC_EXT                                 1008
#define IDC_ASSOCFILE                           1010
#define ID_PLAY                                 1012
#define ID_PAUSE                                1014
#define ID_STOP                                 1016
#define ID_CLEAR                                1018
#define ID_ADDFOLDER                            1019
#define IDC_INTEGR                              1021
#define ID_REWIND                               1022
#define ID_NEXTTRACK                            1024
#define ID_DELDIRA                              1025
#define ID_ABOUT                                1026
#define ID_PREVTRACK                            1027
#define ID_OPEN                                 40000
#define ID_EXIT                                 40001
#define ID_CUT                                  40002
#define ID_MODE_NORMAL                          40003
#define ID_SHOWVIDEO                            40004
#define ID_FULLSCREEN                           40005
#define ID_MODE_REPEATLIST                      40006
#define ID_MODE_REPEATFILE                      40007
#define ID_HOMEPAGE                             40008
#define ID_VOLUMEDOWN                           40009
#define ID_SHOWCOVER                            40011
#define ID_PROP_AUDIO                           40012
#define ID_PROP_VIDEO                           40013
#define ID_PROP_SPLITTER                        40014
#define ID_LOADLIST                             40015
#define ID_SAVELIST                             40016
#define ID_SETTINGS                             40017
#define ID_PROP_AUDIOOUT                        40018
#define ID_PROP_VIDEOOUT                        40019
#define ID_ADDDIR_IMAGES                        40020
#define ID_ADDURL                               40021
#define ID_FILEINFO                             40022
#define IDC_POSITION                            40023
#define IDC_LENGTH                              40025
#define ID_DELFILEA                             40026
#define IDC_REMEMBER_PLAYLIST                   40027
#define ID_ASSOCF                               40028
#define IDC_REMEMBER_POSITION                   40029
#define IDC_SHOW_WALLPAPER                      40030
#define IDC_FILENAME                            40031
#define IDC_DELAY                               40032
#define IDC_CURRENTFILE                         40033
#define ID_MODE_RANDOM                          40034
#define ID_FEEDBACK                             40035
#define ID_PLAY_SELECTED                        40036
#define ID_SHOWPLAYLIST                         40037
#define ID_PASTE                                40038
#define ID_SELECTALL                            40039
#define ID_FILE_INFORMATION                     40040
#define ID_COPY                                 40041
#define ID_PLAYPAUSE                            40042
#define ID_VOLUMEUP                             40043
#define ID_SOURCEREPO                           40044
