name: SMP-CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with MSBuild
      run: |
        & "$Env:Path += ";${Env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"; .\scripts\build.ps1"
    - name: Test
      run: |
        Set-Location -Path .\Debug; & "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" SmallMediaPlayer_Tests.dll /TestCaseFilter:"Owner!=GUI"
